In [ ]:
Create a 10×10 random matrix.
Find:
Largest element
Smallest element
Position (index) of largest element
Position (index) of smallest element
Replace every value greater than 50 with 100 using np.where().
Find the indices of all values greater than 70.
Shuffle a 1D array.
Stack two matrices vertically.
Stack two matrices horizontally.
Split an array into 5 equal parts.
Sort an array.
Find unique values and their counts:

In [12]:
import numpy as np
a = np.random.randint(1,101,size=(10,10))
a

array([[ 40,  12,  58,  62,   7,  59,  67,  25,  67,  87],
       [ 33,  52,   3,  56,  89,  69,  82,  87,  27,  59],
       [ 32,  43,  12,  81,   7,  66,  91,  78,  12,  43],
       [  1,  95,  15,   3,  79,   3,  47,  99,  30,  79],
       [ 12,  61,  12,  96,  22,  97,  96,  57,  11,   9],
       [ 32,  46,  81,  34,  19,  68,  58,   2,  36,  96],
       [ 17,  70, 100,  32,  53,  84,  68,  20,   8,  67],
       [ 93,  41,  89,  59,  62,  58,  67,  89,   3,  74],
       [ 71,  28,  21,  56,  34,  36,  77,  53,  30,  88],
       [ 64,  17,  61,  33,  75,  19,  69,  32,  90,  32]])

In [13]:
print("max:",np.max(a))

max: 100


In [14]:
print("min:",np.min(a))

min: 1


In [38]:
print("max at index:",np.unravel_index(np.argmax(a),a.shape))

max at index: (np.int64(6), np.int64(2))


In [39]:
print("min at index:",np.unravel_index(np.argmin(a),a.shape))

min at index: (np.int64(3), np.int64(0))


In [17]:
np.where(a>50,100,a)

array([[ 40,  12, 100, 100,   7, 100, 100,  25, 100, 100],
       [ 33, 100,   3, 100, 100, 100, 100, 100,  27, 100],
       [ 32,  43,  12, 100,   7, 100, 100, 100,  12,  43],
       [  1, 100,  15,   3, 100,   3,  47, 100,  30, 100],
       [ 12, 100,  12, 100,  22, 100, 100, 100,  11,   9],
       [ 32,  46, 100,  34,  19, 100, 100,   2,  36, 100],
       [ 17, 100, 100,  32, 100, 100, 100,  20,   8, 100],
       [100,  41, 100, 100, 100, 100, 100, 100,   3, 100],
       [100,  28,  21, 100,  34,  36, 100, 100,  30, 100],
       [100,  17, 100,  33, 100,  19, 100,  32, 100,  32]])

In [42]:
indices = np.where(a>70)
print(indices)

(array([0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6, 7, 7, 7, 7,
       8, 8, 8, 9, 9]), array([9, 4, 6, 7, 3, 6, 7, 1, 4, 7, 9, 3, 5, 6, 2, 9, 2, 5, 0, 2, 7, 9,
       0, 6, 9, 4, 8]))


In [28]:
b = np.array([5,8,9,6,3])
np.random.shuffle(b)
b

array([9, 3, 5, 6, 8])

In [25]:
c = np.arange(25).reshape(5,5)
d = np.arange(25,50).reshape(5,5)

print("vstack:",np.vstack((c,d)))

vstack: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [26]:
print("hstack:",np.hstack((c,d)))

hstack: [[ 0  1  2  3  4 25 26 27 28 29]
 [ 5  6  7  8  9 30 31 32 33 34]
 [10 11 12 13 14 35 36 37 38 39]
 [15 16 17 18 19 40 41 42 43 44]
 [20 21 22 23 24 45 46 47 48 49]]


In [43]:
arr = np.arange(20)

np.split(arr,5)

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15]),
 array([16, 17, 18, 19])]

In [30]:
print("sorted:", np.sort(b))

sorted: [3 5 6 8 9]


In [35]:
e = np.random.randint(0,10,50)
print(e)
np.unique(e,return_counts=True)

[3 7 1 4 8 0 2 8 3 8 4 9 6 3 5 9 6 2 8 6 7 9 8 4 5 5 1 1 5 2 1 9 1 5 8 9 8
 5 4 9 1 8 3 1 9 5 9 8 9 3]


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 7, 3, 5, 4, 7, 3, 2, 9, 9]))