In [66]:
import numpy as np

data1 = np.genfromtxt("Iris.csv", delimiter=",", dtype=str)

print(data1)

[['Id' 'SepalLengthCm' 'SepalWidthCm' 'PetalLengthCm' 'PetalWidthCm'
  'Species']
 ['1' '5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['2' '4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['3' '4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4' '4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5' '5.0' '3.6' '1.4' '0.2' 'Iris-setosa']
 ['6' '5.4' '3.9' '1.7' '0.4' 'Iris-setosa']
 ['7' '4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['8' '5.0' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['9' '4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['10' '4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['11' '5.4' '3.7' '1.5' '0.2' 'Iris-setosa']
 ['12' '4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['13' '4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['14' '4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['15' '5.8' '4.0' '1.2' '0.2' 'Iris-setosa']
 ['16' '5.7' '4.4' '1.5' '0.4' 'Iris-setosa']
 ['17' '5.4' '3.9' '1.3' '0.4' 'Iris-setosa']
 ['18' '5.1' '3.5' '1.4' '0.3' 'Iris-setosa']
 ['19' '5.7' '3.8' '1.7' '0.3' 'Iris-setosa']
 ['20' '5.1' '3.8' '1.5' '0.3' 'Iris-setosa']
 ['21' 

In [67]:
header = data1[0]
data = data1[1:]
print(header)
print(data)

['Id' 'SepalLengthCm' 'SepalWidthCm' 'PetalLengthCm' 'PetalWidthCm'
 'Species']
[['1' '5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['2' '4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['3' '4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4' '4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5' '5.0' '3.6' '1.4' '0.2' 'Iris-setosa']
 ['6' '5.4' '3.9' '1.7' '0.4' 'Iris-setosa']
 ['7' '4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['8' '5.0' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['9' '4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['10' '4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['11' '5.4' '3.7' '1.5' '0.2' 'Iris-setosa']
 ['12' '4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['13' '4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['14' '4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['15' '5.8' '4.0' '1.2' '0.2' 'Iris-setosa']
 ['16' '5.7' '4.4' '1.5' '0.4' 'Iris-setosa']
 ['17' '5.4' '3.9' '1.3' '0.4' 'Iris-setosa']
 ['18' '5.1' '3.5' '1.4' '0.3' 'Iris-setosa']
 ['19' '5.7' '3.8' '1.7' '0.3' 'Iris-setosa']
 ['20' '5.1' '3.8' '1.5' '0.3' 'Iris-setosa']
 ['21' '5

In [68]:
num_data = data[:,1:5]
num_data = num_data.astype(float)
print(num_data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [69]:
print("rows:",num_data.shape[0])
print("col:",num_data.shape[1])
print("shape:",num_data.shape)
print("dimension:",num_data.ndim)
print("datatype:", num_data.dtype)
print("size:",num_data.size)



rows: 150
col: 4
shape: (150, 4)
dimension: 2
datatype: float64
size: 600


In [100]:
print("mean:",np.mean(num_data,axis = 0))
print("median:",np.median(num_data,axis = 0))
print("standard deviation:",np.std(num_data,axis = 0))
print("variance:",np.var(num_data,axis = 0))
print("max:",np.max(num_data,axis = 0))
print("min:",np.min(num_data,axis = 0))


mean: [5.84333333 3.054      3.75866667 1.19866667]
median: [5.8  3.   4.35 1.3 ]
standard deviation: [0.82530129 0.43214658 1.75852918 0.76061262]
variance: [0.68112222 0.18675067 3.09242489 0.57853156]
max: [7.9 4.4 6.9 2.5]
min: [4.3 2.  1.  0.1]


In [103]:
b1 = num_data[:,0]> 5
print(num_data[b1])
print("num:",np.sum(b1) ) #sepal length greater than 5

[[5.1 3.5 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [5.4 3.7 1.5 0.2]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [5.1 3.3 1.7 0.5]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [5.5 3.5 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.8 1.6 0.2]
 [5.3 3.7 1.5 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.

In [104]:
b2 = num_data[:,2]> 4
print(num_data[b2])#petal length greater than 4
print("num:",np.sum(b2) )

[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [6.6 2.9 4.6 1.3]
 [5.9 3.  4.2 1.5]
 [6.1 2.9 4.7 1.4]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.9 3.2 4.8 1.8]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [6.8 3.  5.5 2.1]
 [5.7 2.5 5.  2. ]
 [5.8 2.8 5.1 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 3.  5.5 1.8]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.

In [105]:
b3=num_data[:,1]<3
print(num_data[b3])#sepal width smaller than 3
print("num:",np.sum(b3) )

[[4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0.3]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.8 2.8 4.8 1.4]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [6.3 2.3 4.4 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 1.3]
 [5.8 2.7 5.1 1.9]
 [6.3 2.9 5.6 1.8]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [6.4 2.7 5.3 1.9]
 [5.7 2.5 5.  2. ]
 [5.8 2.8 5.1 2.4]
 [7.7 2.6 6.9 2.3]
 [6.  2.2 5.  1.5]
 [5.6 2.8 4.9 2. ]
 [7.7 2.8 6.7 2. ]
 [6.3 2.7 4.9 1.8]
 [6.2 2.8 4.8 1.8]
 [6.4 2.8 5.6 2.1]
 [7.4 2.8 6.1 1.9]
 [6.4 2.8 5.

In [106]:
b4=num_data[:,3]>1.5
print(num_data[b4])#petal width greater than 1.5
print("num:",np.sum(b4) )

[[6.3 3.3 4.7 1.6]
 [5.9 3.2 4.8 1.8]
 [6.7 3.  5.  1.7]
 [6.  2.7 5.1 1.6]
 [6.  3.4 4.5 1.6]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [6.8 3.  5.5 2.1]
 [5.7 2.5 5.  2. ]
 [5.8 2.8 5.1 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 3.  5.5 1.8]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [6.9 3.2 5.7 2.3]
 [5.6 2.8 4.9 2. ]
 [7.7 2.8 6.7 2. ]
 [6.3 2.7 4.9 1.8]
 [6.7 3.3 5.7 2.1]
 [7.2 3.2 6.  1.8]
 [6.2 2.8 4.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.1]
 [7.2 3.  5.8 1.6]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [6.4 2.8 5.6 2.2]
 [7.7 3.  6.1 2.3]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.  3.  4.8 1.8]
 [6.9 3.1 5.4 2.1]
 [6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]
num: 52


In [107]:
b5 = num_data[:,0] > 5
b6 = num_data[:,3]>1
print(num_data[b5&b6])
print("num:",np.sum(b5&b6) )

[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.9 3.  4.2 1.5]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.5 2.4 3.8 1.1]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.

In [76]:
transpose = num_data.T
print(transpose)

[[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
  5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
  5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
  6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
  6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
  5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
  6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
  6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
  6.7 6.7 6.3 6.5 6.2 5.9]
 [3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
  3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
  3.5 3.1 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
  2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8
  2.5 2.8 2.9 3.  2.8 3.  2.9 2.6 2.4 2.4 2.7 2.7 3.  3.4 3.1 2.3 3.  2.5
  2.6 3.  2.

In [77]:
print(num_data*2)

[[10.2  7.   2.8  0.4]
 [ 9.8  6.   2.8  0.4]
 [ 9.4  6.4  2.6  0.4]
 [ 9.2  6.2  3.   0.4]
 [10.   7.2  2.8  0.4]
 [10.8  7.8  3.4  0.8]
 [ 9.2  6.8  2.8  0.6]
 [10.   6.8  3.   0.4]
 [ 8.8  5.8  2.8  0.4]
 [ 9.8  6.2  3.   0.2]
 [10.8  7.4  3.   0.4]
 [ 9.6  6.8  3.2  0.4]
 [ 9.6  6.   2.8  0.2]
 [ 8.6  6.   2.2  0.2]
 [11.6  8.   2.4  0.4]
 [11.4  8.8  3.   0.8]
 [10.8  7.8  2.6  0.8]
 [10.2  7.   2.8  0.6]
 [11.4  7.6  3.4  0.6]
 [10.2  7.6  3.   0.6]
 [10.8  6.8  3.4  0.4]
 [10.2  7.4  3.   0.8]
 [ 9.2  7.2  2.   0.4]
 [10.2  6.6  3.4  1. ]
 [ 9.6  6.8  3.8  0.4]
 [10.   6.   3.2  0.4]
 [10.   6.8  3.2  0.8]
 [10.4  7.   3.   0.4]
 [10.4  6.8  2.8  0.4]
 [ 9.4  6.4  3.2  0.4]
 [ 9.6  6.2  3.2  0.4]
 [10.8  6.8  3.   0.8]
 [10.4  8.2  3.   0.2]
 [11.   8.4  2.8  0.4]
 [ 9.8  6.2  3.   0.2]
 [10.   6.4  2.4  0.4]
 [11.   7.   2.6  0.4]
 [ 9.8  6.2  3.   0.2]
 [ 8.8  6.   2.6  0.4]
 [10.2  6.8  3.   0.4]
 [10.   7.   2.6  0.6]
 [ 9.   4.6  2.6  0.6]
 [ 8.8  6.4  2.6  0.4]
 [10.   7. 

In [78]:
print(num_data/10)

[[0.51 0.35 0.14 0.02]
 [0.49 0.3  0.14 0.02]
 [0.47 0.32 0.13 0.02]
 [0.46 0.31 0.15 0.02]
 [0.5  0.36 0.14 0.02]
 [0.54 0.39 0.17 0.04]
 [0.46 0.34 0.14 0.03]
 [0.5  0.34 0.15 0.02]
 [0.44 0.29 0.14 0.02]
 [0.49 0.31 0.15 0.01]
 [0.54 0.37 0.15 0.02]
 [0.48 0.34 0.16 0.02]
 [0.48 0.3  0.14 0.01]
 [0.43 0.3  0.11 0.01]
 [0.58 0.4  0.12 0.02]
 [0.57 0.44 0.15 0.04]
 [0.54 0.39 0.13 0.04]
 [0.51 0.35 0.14 0.03]
 [0.57 0.38 0.17 0.03]
 [0.51 0.38 0.15 0.03]
 [0.54 0.34 0.17 0.02]
 [0.51 0.37 0.15 0.04]
 [0.46 0.36 0.1  0.02]
 [0.51 0.33 0.17 0.05]
 [0.48 0.34 0.19 0.02]
 [0.5  0.3  0.16 0.02]
 [0.5  0.34 0.16 0.04]
 [0.52 0.35 0.15 0.02]
 [0.52 0.34 0.14 0.02]
 [0.47 0.32 0.16 0.02]
 [0.48 0.31 0.16 0.02]
 [0.54 0.34 0.15 0.04]
 [0.52 0.41 0.15 0.01]
 [0.55 0.42 0.14 0.02]
 [0.49 0.31 0.15 0.01]
 [0.5  0.32 0.12 0.02]
 [0.55 0.35 0.13 0.02]
 [0.49 0.31 0.15 0.01]
 [0.44 0.3  0.13 0.02]
 [0.51 0.34 0.15 0.02]
 [0.5  0.35 0.13 0.03]
 [0.45 0.23 0.13 0.03]
 [0.44 0.32 0.13 0.02]
 [0.5  0.35

In [79]:
print(num_data+1)

[[6.1 4.5 2.4 1.2]
 [5.9 4.  2.4 1.2]
 [5.7 4.2 2.3 1.2]
 [5.6 4.1 2.5 1.2]
 [6.  4.6 2.4 1.2]
 [6.4 4.9 2.7 1.4]
 [5.6 4.4 2.4 1.3]
 [6.  4.4 2.5 1.2]
 [5.4 3.9 2.4 1.2]
 [5.9 4.1 2.5 1.1]
 [6.4 4.7 2.5 1.2]
 [5.8 4.4 2.6 1.2]
 [5.8 4.  2.4 1.1]
 [5.3 4.  2.1 1.1]
 [6.8 5.  2.2 1.2]
 [6.7 5.4 2.5 1.4]
 [6.4 4.9 2.3 1.4]
 [6.1 4.5 2.4 1.3]
 [6.7 4.8 2.7 1.3]
 [6.1 4.8 2.5 1.3]
 [6.4 4.4 2.7 1.2]
 [6.1 4.7 2.5 1.4]
 [5.6 4.6 2.  1.2]
 [6.1 4.3 2.7 1.5]
 [5.8 4.4 2.9 1.2]
 [6.  4.  2.6 1.2]
 [6.  4.4 2.6 1.4]
 [6.2 4.5 2.5 1.2]
 [6.2 4.4 2.4 1.2]
 [5.7 4.2 2.6 1.2]
 [5.8 4.1 2.6 1.2]
 [6.4 4.4 2.5 1.4]
 [6.2 5.1 2.5 1.1]
 [6.5 5.2 2.4 1.2]
 [5.9 4.1 2.5 1.1]
 [6.  4.2 2.2 1.2]
 [6.5 4.5 2.3 1.2]
 [5.9 4.1 2.5 1.1]
 [5.4 4.  2.3 1.2]
 [6.1 4.4 2.5 1.2]
 [6.  4.5 2.3 1.3]
 [5.5 3.3 2.3 1.3]
 [5.4 4.2 2.3 1.2]
 [6.  4.5 2.6 1.6]
 [6.1 4.8 2.9 1.4]
 [5.8 4.  2.4 1.3]
 [6.1 4.8 2.6 1.2]
 [5.6 4.2 2.4 1.2]
 [6.3 4.7 2.5 1.2]
 [6.  4.3 2.4 1.2]
 [8.  4.2 5.7 2.4]
 [7.4 4.2 5.5 2.5]
 [7.9 4.1 5.

In [81]:
# Sort Sepal Length
print(np.sort(num_data[:,0]))

# Sort Petal Width
print(np.sort(num_data[:,3]))

[4.3 4.4 4.4 4.4 4.5 4.6 4.6 4.6 4.6 4.7 4.7 4.8 4.8 4.8 4.8 4.8 4.9 4.9
 4.9 4.9 4.9 4.9 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.1 5.1 5.1 5.1
 5.1 5.1 5.1 5.1 5.1 5.2 5.2 5.2 5.2 5.3 5.4 5.4 5.4 5.4 5.4 5.4 5.5 5.5
 5.5 5.5 5.5 5.5 5.5 5.6 5.6 5.6 5.6 5.6 5.6 5.7 5.7 5.7 5.7 5.7 5.7 5.7
 5.7 5.8 5.8 5.8 5.8 5.8 5.8 5.8 5.9 5.9 5.9 6.  6.  6.  6.  6.  6.  6.1
 6.1 6.1 6.1 6.1 6.1 6.2 6.2 6.2 6.2 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3
 6.4 6.4 6.4 6.4 6.4 6.4 6.4 6.5 6.5 6.5 6.5 6.5 6.6 6.6 6.7 6.7 6.7 6.7
 6.7 6.7 6.7 6.7 6.8 6.8 6.8 6.9 6.9 6.9 6.9 7.  7.1 7.2 7.2 7.2 7.3 7.4
 7.6 7.7 7.7 7.7 7.7 7.9]
[0.1 0.1 0.1 0.1 0.1 0.1 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2
 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.3 0.3
 0.3 0.3 0.3 0.3 0.3 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.5 0.6 1.  1.  1.  1.
 1.  1.  1.  1.1 1.1 1.1 1.2 1.2 1.2 1.2 1.2 1.3 1.3 1.3 1.3 1.3 1.3 1.3
 1.3 1.3 1.3 1.3 1.3 1.3 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.5 1.5 1.5 1.5
 1.5 1.5 1.5 1.5 1.5 1.5 1

In [82]:
print("Sepal Length")

print("Mean:", np.mean(num_data[:,0]))
print("Median:", np.median(num_data[:,0]))
print("Standard Deviation:", np.std(num_data[:,0]))
print("Variance:", np.var(num_data[:,0]))
print("Minimum:", np.min(num_data[:,0]))
print("Maximum:", np.max(num_data[:,0]))

Sepal Length
Mean: 5.843333333333334
Median: 5.8
Standard Deviation: 0.8253012917851409
Variance: 0.6811222222222223
Minimum: 4.3
Maximum: 7.9


In [83]:
print("Sepal Width")

print("Mean:", np.mean(num_data[:,1]))
print("Median:", np.median(num_data[:,1]))
print("Standard Deviation:", np.std(num_data[:,1]))
print("Variance:", np.var(num_data[:,1]))
print("Minimum:", np.min(num_data[:,1]))
print("Maximum:", np.max(num_data[:,1]))

Sepal Width
Mean: 3.0540000000000003
Median: 3.0
Standard Deviation: 0.4321465800705435
Variance: 0.18675066666666668
Minimum: 2.0
Maximum: 4.4


In [84]:
print("Petal Length")

print("Mean:", np.mean(num_data[:,2]))
print("Median:", np.median(num_data[:,2]))
print("Standard Deviation:", np.std(num_data[:,2]))
print("Variance:", np.var(num_data[:,2]))
print("Minimum:", np.min(num_data[:,2]))
print("Maximum:", np.max(num_data[:,2]))

Petal Length
Mean: 3.758666666666666
Median: 4.35
Standard Deviation: 1.7585291834055212
Variance: 3.092424888888889
Minimum: 1.0
Maximum: 6.9


In [85]:
print("Petal width")

print("Mean:", np.mean(num_data[:,3]))
print("Median:", np.median(num_data[:,3]))
print("Standard Deviation:", np.std(num_data[:,3]))
print("Variance:", np.var(num_data[:,3]))
print("Minimum:", np.min(num_data[:,3]))
print("Maximum:", np.max(num_data[:,3]))

Petal width
Mean: 1.1986666666666668
Median: 1.3
Standard Deviation: 0.7606126185881716
Variance: 0.5785315555555555
Minimum: 0.1
Maximum: 2.5


In [96]:
c1 = np.unique(data1[1:,5])
print("unique:",c1)
print("count:",len(c1))

unique: ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
count: 3


In [98]:
print("mean:",np.mean(num_data,axis = 1))
print("median:",np.median(num_data,axis = 1))
print("standard deviation:",np.std(num_data,axis = 1))
print("variance:",np.var(num_data,axis = 1))
print("max:",np.max(num_data,axis = 1))
print("min:",np.min(num_data,axis = 1))
print("sum:",np.sum(num_data,axis = 1))

mean: [2.55  2.375 2.35  2.35  2.55  2.85  2.425 2.525 2.225 2.4   2.7   2.5
 2.325 2.125 2.8   3.    2.75  2.575 2.875 2.675 2.675 2.675 2.35  2.65
 2.575 2.45  2.6   2.6   2.55  2.425 2.425 2.675 2.725 2.825 2.4   2.4
 2.625 2.4   2.225 2.55  2.525 2.1   2.275 2.675 2.8   2.375 2.675 2.35
 2.675 2.475 4.075 3.9   4.1   3.275 3.85  3.575 3.975 2.9   3.85  3.3
 2.875 3.65  3.3   3.775 3.35  3.9   3.65  3.4   3.6   3.275 3.925 3.55
 3.8   3.7   3.725 3.85  3.95  4.1   3.725 3.2   3.2   3.15  3.4   3.85
 3.6   3.875 4.    3.575 3.5   3.325 3.425 3.775 3.4   2.9   3.45  3.525
 3.525 3.675 2.925 3.475 4.525 3.875 4.525 4.15  4.375 4.825 3.4   4.575
 4.2   4.85  4.2   4.075 4.35  3.8   4.025 4.3   4.2   5.1   4.875 3.675
 4.525 3.825 4.8   3.925 4.45  4.55  3.9   3.95  4.225 4.4   4.55  5.025
 4.25  3.925 3.925 4.775 4.425 4.2   3.9   4.375 4.45  4.35  3.875 4.55
 4.55  4.3   3.925 4.175 4.325 3.95 ]
median: [2.45 2.2  2.25 2.3  2.5  2.8  2.4  2.45 2.15 2.3  2.6  2.5  2.2  2.05
 2.6  2.95 2