In [ ]:
#Creating NumPy array

In [6]:
#np.array
import numpy as np
a = np.array([1,2,3])
print(type(a))
print(a)



<class 'numpy.ndarray'>
[1 2 3]


In [12]:
#2D and 3D
b = np.array([[1,2,3],[4,5,6]])
c= np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(b)
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [13]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
#dtype
np.array([1,2,3],dtype=float)


array([1., 2., 3.])

In [21]:
#np.arange
e = np.arange(1,11)
np.arange(1,11,2)


array([1, 3, 5, 7, 9])

In [34]:
#with reshape
np.arange(1,13).reshape(3,2,2)


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [26]:
#np.ones and #np.zeroes (used for fast initialization)
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [29]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
#random between 0 and 1
np.random.random((3,4))

array([[0.81071884, 0.13164516, 0.18077576, 0.78775131],
       [0.36263916, 0.74275449, 0.10259929, 0.82515141],
       [0.90280722, 0.04437063, 0.05970744, 0.0101035 ]])

In [31]:
#np.linspace
np.linspace(-10,10,10)


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [36]:
#np.identity
np.identity(3,dtype = int)


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
#ARRAY ATTRIBUTES

In [43]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [45]:
#ndim gives dimension
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [46]:
#shape gives rows and colomns
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [47]:
#size gives number of items
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [48]:
#itmsize = occupies size in mem
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


In [49]:
#dtype = data type of items
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [ ]:
#changing datatype

In [50]:
#astype
a3.astype(np.int32)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [ ]:
#array operations

In [51]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [53]:
#scalar operation
#arithmetic
print(a1*2)
print(a1+2)
print(a1-2)
print(a1/2)
print(a1**2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [56]:
#relational
print(a2>15)
print(a2==15)



[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False  True]
 [False False False False]
 [False False False False]]


In [59]:
#vector operations
#arithmetic
print(a1*a2)
print(a1+a2)
print(a1/a2)

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


In [ ]:
#ARRAY FUNCTIONS

In [62]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100) #round = round offs
a1

array([[80., 47., 47.],
       [78.,  8., 41.],
       [69., 24., 74.]])

In [67]:
#max/min/sum/prod
#0 -> col and 1-> row
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))
print(np.max(a1,axis=1))
print(np.max(a1,axis=0))


80.0
8.0
468.0
554046481797120.0
[80. 78. 74.]
[80. 47. 74.]


In [68]:
#mean/median/std/var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))
print(np.mean(a1,axis = 1))

52.0
47.0
23.86070689089771
569.3333333333334
[58.         42.33333333 55.66666667]


In [69]:
#trignometric functions
np.sin(a1)

array([[-0.99388865,  0.12357312,  0.12357312],
       [ 0.51397846,  0.98935825, -0.15862267],
       [-0.11478481, -0.90557836, -0.98514626]])

In [70]:
#dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [74]:
#log and exponents
print(np.log(a1))
print(np.exp(a1))

[[4.38202663 3.8501476  3.8501476 ]
 [4.35670883 2.07944154 3.71357207]
 [4.2341065  3.17805383 4.30406509]]
[[5.54062238e+34 2.58131289e+20 2.58131289e+20]
 [7.49841700e+33 2.98095799e+03 6.39843494e+17]
 [9.25378173e+29 2.64891221e+10 1.37338298e+32]]


In [82]:
#round/floor/ceil
a4=np.random.random((2,3))*100
print(a4)
print(np.round(a4))
print(np.floor(a4))
print(np.ceil(a4))

[[73.17866716 45.29774351 71.65861368]
 [83.32775377 37.95883928 65.12269641]]
[[73. 45. 72.]
 [83. 38. 65.]]
[[73. 45. 71.]
 [83. 37. 65.]]
[[74. 46. 72.]
 [84. 38. 66.]]


In [ ]:
#INDEXING and SLICING

In [84]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [86]:
print(a1[-1])

9


In [91]:
print(a2)
print(a2[1,2])


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
6.0


In [93]:
print(a3)
print(a3[1,0,1])
print(a3[1,1,0])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5
6


In [100]:
print(a1[2:5])

[2]


In [108]:
print(a2[0,:])
print(a2[:,2])
print(a2[1:,1:3])

[0. 1. 2. 3.]
[ 2.  6. 10.]
[[ 5.  6.]
 [ 9. 10.]]


In [110]:
print(a2[::2,::3])

[[ 0.  3.]
 [ 8. 11.]]


In [121]:
print(a2[::2,1::2])
print(a2[1,::3])
print(a2[:2,1:])

[[ 1.  3.]
 [ 9. 11.]]
[4. 7.]
[[1. 2. 3.]
 [5. 6. 7.]]


In [122]:
a3=np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [131]:
print(a3[1])
print(a3[::2])


[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [134]:
print(a3[0,1])
print(a3[1,:,1])

[3 4 5]
[10 13 16]


In [135]:
print(a3[2,1:,1:])

[[22 23]
 [25 26]]


In [136]:
print(a3[::2,0,::2])

[[ 0  2]
 [18 20]]


In [ ]:
#ITERATING

In [137]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [138]:
for i in a2:
  print(i)


[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [139]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [140]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [ ]:
#RESHAPING

In [ ]:
#reshape studied above

In [144]:
#transpose
print(np.transpose(a2))
print(a2.T)

[[ 0.  4.  8.]
 [ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]]
[[ 0.  4.  8.]
 [ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]]


In [145]:
#ravel converts in 1D
print(a2.ravel())
print(a3.ravel())


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [ ]:
#STACKING

In [162]:
#horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

print(np.hstack((a4,a5,a4,a5)))

[[ 0  1  2  3 12 13 14 15  0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19  4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23  8  9 10 11 20 21 22 23]]


In [161]:
#vertical stacking
print(np.vstack((a4,a5,a4,a5)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
#SPLITTING

In [160]:
#horizontal splitting
np.hsplit(a4,2)


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [159]:
#vertical splitting
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]