In [ ]:
1. Create a 5×5 matrix of zeros.
2. Create a 4×4 identity matrix.
3. Generate 20 random integers between 1 and 100.
4. Find the mean, median, and standard deviation.
5. Reshape a 1D array into a 3×4 matrix.
6. Select all values greater than 50.
7. Multiply two matrices.
8. Find the maximum value in each row.
9. Reverse an array.
10. Find unique elements in an array.

In [3]:
import numpy as np
#1
a1 = np.zeros((5,5))
print(a1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
#2
a2 = np.identity(4,dtype=int)
print(a2)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [13]:
#3
a3 = np.random.randint(1,101,20)
print(a3)

[96 17 62 31 13  7 66  6 43 20 36 32 95 40 27 61 10 63 66  5]


In [15]:
#4
print(np.mean(a3))
print(np.median(a3))
print(np.std(a3))

39.8
34.0
27.68862582361212


In [16]:
#5
a4 = np.random.randint(1,101,12)
print(a4)
print(a4.reshape(3,4))

[58 12 99 17 19  9 68  2 63 67 51 78]
[[58 12 99 17]
 [19  9 68  2]
 [63 67 51 78]]


In [25]:
#6
print(a4[a4 > 50])


[58 99 68 63 67 51 78]


In [27]:
#7
a5 = np.arange(12).reshape(4,3)
a6 = np.arange(12,24).reshape(3,4)
print(np.dot(a5,a6))


[[ 56  59  62  65]
 [200 212 224 236]
 [344 365 386 407]
 [488 518 548 578]]


In [20]:
#8
np.max(a5,axis = 1)

array([ 2,  5,  8, 11])

In [23]:
#9
np.flip(a4)


array([78, 51, 67, 63,  2, 68,  9, 19, 17, 99, 12, 58])

In [26]:
#10
arr = np.array([1, 2, 3, 2, 4, 1, 5, 3])
print(np.unique(arr))


[1 2 3 4 5]
